version: "3.9"

services:
  db:
    image: postgres:16
    container_name: besmart_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: besmart_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
